services:
  moonrollers:
    build:
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/moonrollers:${GIT_TAG:-dev}
    ports:
      - "23234:23234"
    environment:
      - ASCII_ARCADE_LANG="EN"
    restart: always
    volumes:
      - ssh:/app/.ssh

volumes:
  ssh:
