services:
  moonrollers:
    build:
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/moonrollers:${GIT_TAG:-dev}
    ports:
      - ${SSH_PORT:-2222}:${ASCII_ARCADE_SSH_PORT:-2222}
      - ${WEB_PORT:-8080}:${ASCII_ARCADE_WEB_PORT:-8080}
    env_file:
      - .env
    restart: always
    volumes:
      - moonrollers_ssh:/app/.ssh
volumes:
  moonrollers_ssh:
